# This Dockerfile builds an image for development.
FROM debian:buster

# Note: this only exposes the port to other docker containers.
EXPOSE 80 443

WORKDIR /opt/certbot/src

# TODO: Install Apache/Nginx for plugin development.
COPY . .
RUN apt-get update
RUN    apt-get install apache2 git nginx-light -y
RUN    letsencrypt-auto-source/letsencrypt-auto --os-packages-only
RUN    apt-get clean
RUN    rm -rf /var/lib/apt/lists/*   /tmp/*    /var/tmp/*

RUN VENV_NAME="../venv" python tools/venv.py

ENV PATH /opt/certbot/venv/bin:$PATH
